<?php

function gsearch_help($path, $arg){
	if($path == 'admin/help#gsearch'){
		return t('Google search integration.');
	}
}

function gsearch_block_info(){
	$blocks = array();
	$blocks['google_integration'] = array(
		'info' => t('Integration with Google search.'),
		'cache' => DRUPAL_NO_CACHE,
		);
	return $blocks;
}

function gsearch_block_view($block_name = ''){
	if ($block_name = 'google_integration'){
		//NOTE: drupal_lookup_path is a D7 function; for D6, it would be node_valid_path
		$path = drupal_lookup_path('source', 'gsearch_results');
		if(!$path){
                        //this create the search results page if it doesn't exist
			$node = new stdClass(); 
			$node->type = "page"; 
			$node->title = "Search Results";
			$node->language = LANGUAGE_NONE; 
			$node->path = array('alias' => 'gsearch_results'); 
			node_object_prepare($node); 
			$node->uid = 1; 
			$node->body[$node->language][0]['format'] = 'php_code';
			$node->body[$node->language][0]['summary'] = 'UC Merced Site Search';
			$node->body[$node->language][0]['value'] = '<gcse:search linktarget="_parent"
				queryParameterName="q_as">
				</gcse:search>';
			$node = node_submit($node); 
			node_save($node);
			}
                //content that will be displayed in block (i.e., the search box)
		$content = <<<EOT
    
                <!-- Put the following javascript before the closing </head> tag. -->
  
                <script>
                (function() {
                    var cx = '017536680796664338934:5pfh-ddinpm';
                    var gcse = document.createElement('script'); gcse.type = 'text/javascript'; gcse.async = true;
                    gcse.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') +
                        '//www.google.com/cse/cse.js?cx=' + cx;
                    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(gcse, s);
                })();
                </script>
                <!-- Place this tag where you want the search box to render -->
                <gcse:searchbox-only></gcse:searchbox-only>
EOT;

		//$content .= '<gcse:searchbox-only linktarget="http://bryit.campuscms.ucmerced.edu/gsearch_results" queryParameterName="q_as"></gcse:searchbox-only>';
		$block = array (
			'content' => $content,
			);
                //just a comment
		return $block;
		

		
	}
}

