<?php
//gsearch module for campuscms - version 1.0
//author: Bryan green
//revision: 7/10/2013

function gsearch_permission(){
    return array(
      'administer gsearch settings' => array(
          'title' => t('Administer gSearch settings'),
      )  
    );
}

function gsearch_help($path, $arg){
  if($path == 'admin/help#gsearch'){
    return t('Google search integration.');
  }
}

function gsearch_menu(){
    $items = array();
    $items['admin/config/gsearch'] = array(
      'title' => 'gSearch module settings',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('gsearch_form'),
        'access arguments' => array('administer gsearch settings'),
      'type' => MENU_NORMAL_ITEM,
    );
    
    $items['admin/config/gsearch/manage'] = array(
      'title' => 'Manage module configuration',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('gsearch_form'),
        'access arguments' => array('administer gsearch settings'),
      'type' => MENU_NORMAL_ITEM,
    );
    
    return $items;
}

function gsearch_form($form, &$form_state){
    $form['cse_key'] = array(
      '#type' => 'textfield',
        '#title' => t('Google Custom Search ID'),
        '#size' => 32,
        '#default' => variable_get('cse_key'),
        '#required' => TRUE,
    );

    return system_settings_form($form);
}

function gsearch_block_info(){
	$blocks = array();
	$blocks['google_integration'] = array(
		'info' => t('Integration with Google search.'),
		'cache' => DRUPAL_NO_CACHE,
		);
	return $blocks;
}

function gsearch_block_view($block_name = ''){
	if ($block_name == 'google_integration'){
		//NOTE: drupal_lookup_path is a D7 function; for D6, it would be node_valid_path
		$path = drupal_lookup_path('source', 'gsearch_results');
		if(!$path){
                        //this create the search results page if it doesn't exist
			$node = new stdClass(); 
			$node->type = "page"; 
			$node->title = "Search Results";
			$node->language = LANGUAGE_NONE; 
			$node->path = array('alias' => 'gsearch_results'); 
			node_object_prepare($node); 
			$node->uid = 1; 
			$node->field_page_body[$node->language][0]['format'] = 'php_code';
			$node->field_page_body[$node->language][0]['summary'] = 'UC Merced Site Search';
			$node->field_page_body[$node->language][0]['value'] = <<<EOT

			<gcse:search linktarget="_parent" queryParameterName="q_as"></gcse:search>

EOT;
			$node = node_submit($node); 
			node_save($node);
			}
                //content that will be displayed in block (i.e., the search box)
		$search_key = variable_get('cse_key');
                        $content = <<<EOT

    	<script>
			  (function() {
			    var cx = '$search_key';
			    var gcse = document.createElement('script'); gcse.type = 'text/javascript'; gcse.async = true;
			    gcse.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') +
			        '//www.google.com/cse/cse.js?cx=' + cx;
			    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(gcse, s);
			  })();
			</script>
        <form name="GoogleSearch" method="GET" action="/gsearch_results"><input type="text" name="q_as" /><input type="submit" /></form>
        
EOT;

		$block = array (
			'content' => $content,
			);
                //just a comment
		return $block;

	}
}
